// <auto-generated />
namespace Data.DAL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtest));
        
        string IMigrationMetadata.Id
        {
            get { return "201811100328459_addtest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
