// <auto-generated />
namespace Data.DAL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adfd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adfd));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111417466_adfd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
